package manager

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/oheco/oheco/internal/catalog"
)

func launcherScript(rel string) []byte {
	quoted := "'" + strings.ReplaceAll(rel, "'", "'\\''") + "'"
	return []byte("#!/bin/sh\n# Generated by oo; execute the original command name.\n" +
		"oo_launcher=$(readlink -f -- \"$0\") || exit 1\n" +
		"exec \"${oo_launcher%/*}/../\"" + quoted + " \"$@\"\n")
}

func createLaunchers(directory string, a catalog.Artifact) error {
	if len(a.Launchers) == 0 {
		return nil
	}
	dir := filepath.Join(directory, catalog.LauncherDirectory)
	// Archives cannot supply this directory, even if they declare no launchers.
	if err := os.Mkdir(dir, 0755); err != nil {
		return err
	}
	for _, name := range a.Launchers {
		filename := filepath.Join(dir, name)
		if err := os.WriteFile(filename, launcherScript(a.Binaries[name]), 0755); err != nil {
			return err
		}
		if err := os.Chmod(filename, 0755); err != nil {
			return err
		}
	}
	return verifyInstalled(directory, a)
}

func verifyInstalled(directory string, a catalog.Artifact) error {
	if err := verifyBinaries(directory, a); err != nil {
		return err
	}
	if len(a.Launchers) == 0 {
		return nil
	}
	dir := filepath.Join(directory, catalog.LauncherDirectory)
	info, err := os.Lstat(dir)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("launcher directory was replaced: %s", dir)
	}
	for _, name := range a.Launchers {
		filename := filepath.Join(dir, name)
		info, err := os.Lstat(filename)
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() || info.Mode().Perm()&0111 == 0 || info.Size() != int64(len(launcherScript(a.Binaries[name]))) {
			return fmt.Errorf("launcher was modified: %s", filename)
		}
		data, err := os.ReadFile(filename)
		if err != nil {
			return err
		}
		if !bytes.Equal(data, launcherScript(a.Binaries[name])) {
			return fmt.Errorf("launcher was modified: %s", filename)
		}
	}
	return nil
}
